apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_TRANSACTIONS_HOST: https://transactions.apps.cluster.example
  VITE_ANALYTICS_HOST: https://analytics.apps.cluster.example
  VITE_BANK_HOST: https://bank.apps.cluster.example
